#ifndef RR_LIBS_COMMON_CONFIG_H
#define RR_LIBS_COMMON_CONFIG_H

#define RR_LIBS_COMMON_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RR_LIBS_COMMON_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RR_LIBS_COMMON_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif // RR_LIBS_COMMON_CONFIG_H
