#ifndef RR_RUNTIME_CONFIG_H
#define RR_RUNTIME_CONFIG_H

#define RR_RUNTIME_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RR_RUNTIME_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RR_RUNTIME_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define RR_RUNTIME_BIN_DIR "@RR_RUNTIME_BIN_DIR@"
#define RR_RUNTIME_LIB_DIR "@RR_RUNTIME_LIB_DIR@"
#define RR_RUNTIME_ARCHIVE_DIR "@RR_RUNTIME_ARCHIVE_DIR@"
#define RR_RUNTIME_SHARED_DATA_DIR "@RR_RUNTIME_SHARED_DATA_DIR@"
#define RR_RUNTIME_SHARED_CONFIG_DIR "@RR_RUNTIME_SHARED_CONFIG_DIR@"

#define RR_RUNTIME_USER_CONFIG_DIR "@RR_RUNTIME_USER_CONFIG_DIR@"
#define RR_RUNTIME_USER_DATA_DIR "@RR_RUNTIME_USER_DATA_DIR@"

#endif // RR_RUNTIME_CONFIG_H
