#ifndef RR_RUNTIME_CONFIG_H
#define RR_RUNTIME_CONFIG_H

#define RR_RUNTIME_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RR_RUNTIME_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RR_RUNTIME_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define RR_RUNTIME_APP_NAME "@PROJECT_NAME@"
#define RR_RUNTIME_RELATIVE_DATA_DIR   "@RR_RUNTIME_RELATIVE_DATA_DIR@"
#define RR_RUNTIME_RELATIVE_CONFIG_DIR "@RR_RUNTIME_RELATIVE_CONFIG_DIR@"

#endif // RR_RUNTIME_CONFIG_H
