#ifndef RR_LIB_CORE_CONFIG_H
#define RR_LIB_CORE_CONFIG_H

#define RR_LIB_CORE_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RR_LIB_CORE_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RR_LIB_CORE_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif // RR_LIB_CORE_CONFIG_H
