#ifndef RR_EDITOR_CONFIG_H
#define RR_EDITOR_CONFIG_H

#define RR_EDITOR_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RR_EDITOR_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RR_EDITOR_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define RR_EDITOR_RELATIVE_DATA_DIR   "@RR_EDITOR_RELATIVE_DATA_DIR@"
#define RR_EDITOR_RELATIVE_CONFIG_DIR "@RR_EDITOR_RELATIVE_CONFIG_DIR@"

#endif // RR_EDITOR_CONFIG_H
