#ifndef RR_EDITOR_CONFIG_H
#define RR_EDITOR_CONFIG_H

#define RR_RELATIVE_SANDBOX_DATA_DIR   "@RR_RELATIVE_SANDBOX_DATA_DIR@"
#define RR_RELATIVE_SANDBOX_CONFIG_DIR "@RR_RELATIVE_SANDBOX_CONFIG_DIR@"

#endif // RR_EDITOR_CONFIG_H
